"""adding goal

Revision ID: 8b7704cd84fa
Revises: 8d78cb4bee3e
Create Date: 2023-10-25 18:39:36.318411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7704cd84fa'
down_revision = '8d78cb4bee3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('Goal_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('Goal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###
